server:
  port: 8082
springdoc:
  swagger-ui:
    enabled: true
spring:
  datasource:
    url: jdbc:h2:./.local-db/data
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      path: /db
      enabled: true
