-- changeset Ralf Ueberfuhr:1
CREATE TABLE AVATARS (UUID UUID NOT NULL, CONTENT BINARY LARGE OBJECT, HEIGHT INT NOT NULL, NAME VARCHAR(255), WIDTH INT NOT NULL, CONSTRAINT CONSTRAINT_4 PRIMARY KEY (UUID));
CREATE TABLE CUSTOMERS (UUID UUID NOT NULL, NAME VARCHAR(255), STATE VARCHAR(255), AVATAR_UUID UUID, CONSTRAINT CONSTRAINT_6 PRIMARY KEY (UUID));
CREATE TABLE CUSTOMER_INTERESTS (CUSTOMER_UUID UUID NOT NULL, INTERESTS VARCHAR(255));
CREATE TABLE ORDERPRODUCTS (COUNT INT NOT NULL, PRODUCT_UUID UUID NOT NULL, ORDER_UUID UUID NOT NULL);
CREATE TABLE ORDERS (UUID UUID NOT NULL, DATE date, NR VARCHAR(255), PRICE BIGINT NOT NULL, CUSTOMER_UUID UUID, CONSTRAINT CONSTRAINT_8 PRIMARY KEY (UUID));
CREATE TABLE PRODUCTS (UUID UUID NOT NULL, NAME VARCHAR(255), PRICE BIGINT NOT NULL, CONSTRAINT CONSTRAINT_F PRIMARY KEY (UUID));
ALTER TABLE ORDERPRODUCTS ADD CONSTRAINT CONSTRAINT_E PRIMARY KEY (ORDER_UUID, PRODUCT_UUID);
CREATE INDEX FKDMTL3IBS8KLTFPYEX6WIR1CDA_INDEX_7 ON CUSTOMER_INTERESTS(CUSTOMER_UUID);
CREATE INDEX FKF0T930R65D3LL9NNW9V15BINA_INDEX_E ON ORDERPRODUCTS(PRODUCT_UUID);
CREATE INDEX FKNDJ6EYP8BBFMDF4SNE5NKWSW9_INDEX_E ON ORDERPRODUCTS(ORDER_UUID);
CREATE INDEX FKODDQ6PGHWNRMDKNM8VOL4LSSE_INDEX_8 ON ORDERS(CUSTOMER_UUID);
CREATE INDEX FKSAMH6UAW0VNDIKFXWYVYYI88E_INDEX_6 ON CUSTOMERS(AVATAR_UUID);
ALTER TABLE CUSTOMER_INTERESTS ADD CONSTRAINT FKDMTL3IBS8KLTFPYEX6WIR1CDA FOREIGN KEY (CUSTOMER_UUID) REFERENCES CUSTOMERS (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE ORDERPRODUCTS ADD CONSTRAINT FKF0T930R65D3LL9NNW9V15BINA FOREIGN KEY (PRODUCT_UUID) REFERENCES PRODUCTS (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE ORDERPRODUCTS ADD CONSTRAINT FKNDJ6EYP8BBFMDF4SNE5NKWSW9 FOREIGN KEY (ORDER_UUID) REFERENCES ORDERS (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE ORDERS ADD CONSTRAINT FKODDQ6PGHWNRMDKNM8VOL4LSSE FOREIGN KEY (CUSTOMER_UUID) REFERENCES CUSTOMERS (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE CUSTOMERS ADD CONSTRAINT FKSAMH6UAW0VNDIKFXWYVYYI88E FOREIGN KEY (AVATAR_UUID) REFERENCES AVATARS (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT;

